# Generated by Django 4.1.7 on 2023-03-30 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("twitch_id", models.PositiveIntegerField(editable=False, unique=True)),
                ("twitch_name", models.CharField(max_length=25, unique=True)),
                ("banned", models.BooleanField(default=False)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[("1", "User"), ("2", "Moderator"), ("3", "Admin")],
                        default="1",
                    ),
                ),
                ("blocks_placed", models.PositiveIntegerField(default=0)),
                ("last_placement", models.PositiveBigIntegerField(default=0)),
                ("refresh_token", models.CharField(default="", max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
