# Generated by Django 4.1.7 on 2023-03-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_placement",
            field=models.FloatField(default=0),
        ),
    ]
