# Generated by Django 4.1.7 on 2024-11-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="twitch_name",
            new_name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.PositiveIntegerField(
                db_index=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
