# Generated by Django 4.1.7 on 2024-11-27 17:58

from django.db import migrations
from main.models import UserPermissionsField


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_twitch_name_user_username_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=UserPermissionsField(default=0),
        ),
    ]
