# Generated by Django 4.1.7 on 2024-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="auto_remove_afk",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="can_receive_money",
            field=models.BooleanField(default=True),
        ),
    ]
