# Generated by Django 4.1.7 on 2024-11-27 18:08

from main.models import UserPermissionsField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_usersettings_auto_remove_afk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="permissions",
            field=UserPermissionsField(default=None, null=True),
        ),
    ]
