# Generated by Django 4.1.7 on 2024-12-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_userosudata_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="command",
            name="args",
            field=models.JSONField(default=list),
        ),
    ]
