# Generated by Django 4.1.7 on 2024-12-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_command_args"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="channelcommand",
            constraint=models.UniqueConstraint(
                fields=("channel", "command"), name="channel_command_unique"
            ),
        ),
    ]
