# Generated by Django 4.1.7 on 2024-12-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_channelcommand_channel_command_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userosudata",
            name="global_rank",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
