# Generated by Django 4.1.7 on 2024-12-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_userchannelconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchannel",
            name="is_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userchannel",
            name="is_offline_only",
            field=models.BooleanField(default=True),
        ),
    ]
